import { readFileSync, readdirSync, statSync, writeFileSync, appendFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

import { detectDrift, type Baseline, type DriftReport } from "./drift.js";
import { toMarkdown } from "./format.js";

export interface RunnerEnv {
  inputs: Record<string, string | undefined>;
  GITHUB_OUTPUT?: string;
  GITHUB_EVENT_NAME?: string;
  GITHUB_REPOSITORY?: string;
  GITHUB_EVENT_PATH?: string;
  readFile?: (path: string) => string;
  readDir?: (path: string) => string[];
  isFile?: (path: string) => boolean;
  exists?: (path: string) => boolean;
  writeFile?: (path: string, content: string) => void;
  postComment?: (args: { token: string; repo: string; issueNumber: number; body: string }) => Promise<void>;
  write?: (line: string) => void;
}

export interface RunnerResult {
  exitCode: 0 | 1;
  report: DriftReport;
  baselineUpdated: boolean;
  commentPosted: boolean;
  reason?: string;
}

function walk(
  dir: string,
  list: (path: string) => string[],
  isFile: (path: string) => boolean
): string[] {
  const out: string[] = [];
  for (const entry of list(dir)) {
    if (entry.startsWith(".")) continue;
    const full = join(dir, entry);
    if (isFile(full)) {
      if (entry.endsWith(".json")) out.push(full);
    }
  }
  return out.sort();
}

export async function run(env: RunnerEnv): Promise<RunnerResult> {
  const dir = required(env.inputs, "dir");
  const baselinePath = env.inputs.baseline ?? join(dir, ".kg-hashes.json");
  const updateBaseline = (env.inputs.update_baseline ?? "false").toLowerCase() === "true";
  const commentOnPr = env.inputs.comment_on_pr ?? "auto";
  const failOnDrift = (env.inputs.fail_on_drift ?? "true").toLowerCase() !== "false";
  const token = env.inputs.github_token ?? "";

  const read = env.readFile ?? ((p) => readFileSync(p, "utf8"));
  const list = env.readDir ?? ((p) => readdirSync(p));
  const isFile = env.isFile ?? ((p) => statSync(p).isFile());
  const exists = env.exists ?? ((p) => existsSync(p));
  const writeF = env.writeFile ?? ((p, c) => writeFileSync(p, c, "utf8"));
  const write = env.write ?? ((line) => process.stdout.write(`${line}\n`));

  // Collect files
  const paths = walk(dir, list, isFile);
  const files = paths.map((p) => ({ path: relative(dir, p).replace(/\\/g, "/"), raw: read(p) }));

  // Load baseline
  let baseline: Baseline | null = null;
  if (exists(baselinePath)) {
    try {
      baseline = JSON.parse(read(baselinePath)) as Baseline;
    } catch {
      baseline = null;
    }
  }

  const report = detectDrift(files, baseline);
  const markdown = toMarkdown(report);

  setOutput(env, "total-files", String(report.files));
  setOutput(env, "drifted-files", String(report.driftedFiles.length));
  setOutput(env, "new-files", String(report.newFiles.length));
  setOutput(env, "removed-files", String(report.removedFiles.length));

  write(`\n${markdown}\n`);

  // Optionally write/update baseline
  let baselineUpdated = false;
  if (updateBaseline) {
    const newBaseline: Baseline = {
      hashes: report.currentHashes,
      generated_at: report.generatedAt
    };
    writeF(baselinePath, JSON.stringify(newBaseline, null, 2) + "\n");
    baselineUpdated = true;
  }

  // PR comment
  const isPullRequest = env.GITHUB_EVENT_NAME === "pull_request";
  const wantsComment = commentOnPr === "true" || (commentOnPr === "auto" && isPullRequest);
  let commentPosted = false;
  let reason: string | undefined;

  if (wantsComment) {
    if (!token) {
      reason = "no github-token provided";
    } else if (!env.GITHUB_EVENT_PATH) {
      reason = "no GITHUB_EVENT_PATH";
    } else if (!env.GITHUB_REPOSITORY) {
      reason = "no GITHUB_REPOSITORY";
    } else {
      const event = JSON.parse(read(env.GITHUB_EVENT_PATH)) as { number?: number; pull_request?: { number?: number } };
      const issueNumber = event.number ?? event.pull_request?.number;
      if (!issueNumber) {
        reason = "no PR number in event payload";
      } else {
        const body = `${markdown}\n\n_Generated by [kg-suite-canonicalize-action](https://github.com/mizcausevic-dev/kg-suite-canonicalize-action)._`;
        const poster = env.postComment ?? defaultPostComment;
        await poster({ token, repo: env.GITHUB_REPOSITORY, issueNumber, body });
        commentPosted = true;
      }
    }
  }

  if (failOnDrift && report.driftedFiles.length > 0) {
    write(`::error::Suite canonical-hash drift: ${report.driftedFiles.length} file(s) drifted from baseline.`);
    return { exitCode: 1, report, baselineUpdated, commentPosted, reason };
  }

  return { exitCode: 0, report, baselineUpdated, commentPosted, reason };
}

function required(inputs: Record<string, string | undefined>, name: string): string {
  const v = inputs[name];
  if (!v || v.length === 0) throw new Error(`input "${name}" is required`);
  return v;
}

function setOutput(env: RunnerEnv, key: string, value: string): void {
  if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

async function defaultPostComment(args: { token: string; repo: string; issueNumber: number; body: string }): Promise<void> {
  const r = await fetch(`https://api.github.com/repos/${args.repo}/issues/${args.issueNumber}/comments`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${args.token}`,
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({ body: args.body })
  });
  if (!r.ok) throw new Error(`GitHub API comment failed: ${r.status} ${await r.text()}`);
}
